[package]
name = "robo-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
iced = { version = "0.12.1", features = ["tokio"] }
tokio = { version = "1.37.0", features = ["full"] }
tokio-serial = "5.4.4"
